### ISSUE TITLE
[lfx-mentorship] Continue dashboard developing after onboarding

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/dashboard#10]
**What would you like to be added**:
The initial version of `karmada-dashboard` just getting on board, and more pages waiting for development.
Welcome front-end developers join us and contribute to this project!

**Goals**
- Design the prototype of the dashboard and the prototype will be placed in the repo.
- Split development tasks into small interaction items and make a plan to iterate the tasks.
  - Note: Not all items are required to be finished within the LFX cycle.
  - The mentor and the maintainers of this project will help figure out the scope that should be included in the LFX project.
- The CI(continuous integration) should be set up along with the dashboard development work.
- Enhance the documents, such as user guide/README.

> Note: 
> 1. The architecture of Karmada project is pretty similar to the Kubernetes, so it is recommended to investigate the [Kubernetes dashboard](https://github.com/kubernetes/dashboard) first.
> 2. The previous prototype might be not terribly helpful, we can design it from scratch.
> 3. The framework can be changed(such as ReactJs) as well if there is a need.

**Mentee**:
There are several mentees who applied to this project, but I can only select one fit(mentee) for this project(correct me if not right). All mentees are welcome to apply in the following LFX or GSoC cycles.

**Comment by vibgreon** [comment]
Hi, @RainbowMango i want to work on this issue for LFX this spring, i am trying to setup karmada on my system meanwhile can you list components/pages we have to add in the dashboard.

**Comment by RainbowMango** [comment]
We have a very draft design document, that might not helpful so much, I'll get it from the author and post it here later.

But I think the [Kubernetes Dashboard](https://github.com/kubernetes/dashboard) would be a great reference.

**Comment by kayceeDev** [comment]
@RainbowMango ,  This will be an awesome challenge. I will like to work on the front-end too. How do I actually get started to fully understand what is needed?

**Comment by Jassi10000** [comment]
@RainbowMango Hey , would love to work on this issue in LFX Spring Mentoship , but don't have Kubernetes knowledge , can I still apply to the program ?
as am still a college undergrad but would really love to get in and learn as much as possible

**Comment by RainbowMango** [comment]
Hi guys @vibgreon @kayceeDev @Jassi10000 
I've just updated the issue description to explain the goals of the program. 
By the way, I'm reviewing the mentee's applications and will contact you by the end of this week.

**Comment by Jassi10000** [comment]
> Hi guys @vibgreon @kayceeDev @Jassi10000 I've just updated the issue description to explain the goals of the program. By the way, I'm reviewing the mentee's applications and will contact you by the end of this week.

@RainbowMango Sir , I was not able to submit my application as I had some issues with my account which I got it resolved from the support team yesterday only . But now I can see it's not accepting applications 😥 . Can I submit my application in some other way ?

**Comment by RainbowMango** [comment]
> Can I submit my application in some other way ?

@Jassi10000 Sorry to hear that. I can't see your application on the mentee list, and I don't know how to submit it.

**Comment by Jassi10000** [comment]
> > Can I submit my application in some other way ?
> 
> @Jassi10000 Sorry to hear that. I can't see your application on the mentee list, and I don't know how to submit it.

No no you don't have to submit it , I want to submit it , but applications are closed , is there any other way I can submit it like forwarding my profile to you personally on mail id or somewhere else to be considered as an intern on this project

**Comment by RainbowMango** [comment]
> is there any other way I can submit it like forwarding my profile to you personally on mail id or somewhere else to be considered as an intern on this project

I don't think so. According to the selection process, the final decision will be done on the system, it won't work if your application is not in the system.

**Comment by Jassi10000** [comment]
> > is there any other way I can submit it like forwarding my profile to you personally on mail id or somewhere else to be considered as an intern on this project
> 
> I don't think so. According to the selection process, the final decision will be done on the system, it won't work if your application is not in the system.

I think I have to wait now for the summer cohort of LFX Mentorship  2022 to get into this 
But anyways I will start contributing from now on ,as project seems interesting 
Will help me in future

**Comment by Zhuzhenghao** [comment]
So, I would love to work on this issue after the prototype is complete.

**Comment by RainbowMango** [comment]
@Zhuzhenghao Long time no see.

Definitely yes!!! I can invite you to review the prototype once it is ready.

**Comment by Zhuzhenghao** [comment]
> @Zhuzhenghao Long time no see.
> 
> Definitely yes!!! I can invite you to review the prototype once it is ready.

Waiting for invitation~
😁

**Comment by RainbowMango** [comment]
@chinmaym07 We can post the prototype here for common review.

**Comment by chinmaym07** [comment]
Hello everyone...
I have designed few screens for the karmada dashboard & working on some other screens like settings,  
We would like you all to review & provide your reviews on each of the screens.
We welcome suggestions, features from everyone that could enhance the prototype.  

Figma file:
https://www.figma.com/file/lEDkjr4gdIn35BSi1hXAGT/Karmada?node-id=0%3A1

**Comment by RainbowMango** [comment]
@chinmaym07 are you ready to submit the PR?

**Comment by chinmaym07** [comment]
Yes sir .. Finished the login screen & creating the PR for the same by today.

**Comment by Amishakumari544** [comment]
@chinmaym07 hi can I join you for the UI/UX design?

**Comment by chinmaym07** [comment]
Yes sure @Amishakumari544 you can .
You can start exploring the designs that we have as of now.
