### ISSUE TITLE
Remove the old implementation of dashboard

### ISSUE THREAD

**Issue by warjiang** [karmada-io/dashboard#107]
**What would you like to be added**:
Remove the old implementation code of dashboard, clean the code.

**Why is this needed**:
The old implementation of dashboard will make the contributor confused, the new implementaion is more powerful than the old one, which have clear roadmap, so we prepare to remove the old code before the release the brand new version of karmada dashboard.

**Comment by warjiang** [comment]
@jayesh9747

**Comment by jayesh9747** [comment]
@warjiang  can you assign  me this issue?
