### ISSUE TITLE
Config the account for sentry

### ISSUE THREAD

**Issue by warjiang** [karmada-io/dashboard#123]
**What would you like to be added**:
We are apply for sentry which is free for opensource project,  sentry replied that 
1. we should create a sentry account
2. convert the account into a sponsored one.

The replied email:
![image](https://github.com/user-attachments/assets/7a0a7800-c674-4535-9c6a-2faab6231dca)

**Why is this needed**:
Because we want to use sentry for debugging
The process of introduce sentry will be tracked in the issue #122

**Comment by warjiang** [comment]
All of the task is that creating sentry account, and I'll finish the next step.
sentry:  https://sentry.io/welcome/
sentry plan for opensource project:  https://sentry.io/for/open-source/
account register: https://sentry.io/auth/login/

**Comment by RainbowMango** [comment]
OK, no problem! I will take a look at it.

**Comment by RainbowMango** [comment]
I‘m not familiar with the tool, would you please give a brief introduction about it at the next dashboard meeting?

**Comment by warjiang** [comment]
> I‘m not familiar with the tool, would you please give a brief introduction about it at the next dashboard meeting?

It's ok. I made a simple notes about sentry, you can view the notes if you like 👉🏻 https://dingwenjiang.notion.site/sentry-10425bd1f17780df968cfbbff117bf5f?pvs=25

apart from basic introduce, also made a show-case to solve the problem just occured:
issue link: https://github.com/karmada-io/dashboard/issues/120
and the corresponding solution:
 ![image](https://github.com/user-attachments/assets/58d9b876-4b05-4a0e-9e84-949e3c7f9469)

**Comment by warjiang** [comment]
We need extra configurations to control whether to enable error report. For some sensitive users, maybe they don't want to report any thing to the public platform, or maybe they have self-hosted sentry, we need to report to the self-hosted sentry.

**Comment by RainbowMango** [comment]
Done.
Created the account and sent the invitation to you.

/close
