### ISSUE TITLE
Add Cypress support for E2E

### ISSUE THREAD

**Issue by vibgreon** [karmada-io/dashboard#13]
## Description

As of now, the project lacks any core E2E testing. We would need a consistent E2E testing strategy to test our features over CI before rolling it out in production.

I would like it to use [Cypress](https://cypress.io/). The contributor who is planning on doing it should plan the core features that need to be tested, identify the user story and integrate this with the CI.

Cypress is a JavaScript-based end-to-end testing framework that doesn’t use Selenium at all. Cypress uses a BDD/TDD (Behavior Driven Development/ Test Driven Development) assertion library and a browser that can be paired with any JavaScript testing framework.

**Comment by vibgreon** [comment]
@RainbowMango I want to work on this issue even K8s dashboard uses Cypress for E2E testing wdyt?

**Comment by RainbowMango** [comment]
+1
Impressive for your activity.

**Comment by RainbowMango** [comment]
/close
Please re-open it if you think this is still needed. Thanks.
