### ISSUE TITLE
[lfx] Develop Override policy, Resource Binding, Work Page

### ISSUE THREAD

**Issue by chinmaym07** [karmada-io/dashboard#15]
**What would you like to be added**:

Develop & enhance the Override Policy, Resource Binding, Work Pages for the Dashboard Project.

**Figma Design**: 
> https://www.figma.com/file/nAhWBN06v6hMCHDlIT9mzk/KARMADA?node-id=6%3A132

**Why is this needed**:
These pages on the web dashboard will help to perform different operations for Override policies, Resource Binding in karmada.

**Comment by Neelesh2512** [comment]
![Screenshot from 2022-05-10 20-57-03](https://user-images.githubusercontent.com/77741561/167665358-cc1f4f57-38f5-4eed-88b3-0b5d4e8536b3.png)
@chinmaym07  I am interested in this project and have past experience with mentioned tech stack also. I was checking the given Figma link but it seems like the provided file is missing.

**Comment by Prakhar-Jaju** [comment]
@Neelesh2512  same problem with me too, @chinmaym07  @RainbowMango please help us.

**Comment by chinmaym07** [comment]
Hi @Neelesh2512, @Prakhar-Jaju  Thankyou for showing interest 💯.
I have created the figma designs for Override policy, Resource Binding, and Work Page design is in progress. For these you'll have to develop these pages & enhance the existing designs in any way like UX or UI.

I have edited the figma file permissions. Everyone will be able to access it now.

AFAIK most of the work will be using the API's provided by the kamada for different functionalities like login, CRUD operations for different type of resources. So you'll have to get a better understanding of the API's that you are using.

**Comment by Taiwrash** [comment]
This also interest me and I will love to be part of this.

**Comment by aminoxix** [comment]
@chinmaym07: Would love to take this issue within LFX Mentorship Program, and work till the completion of assigned tasks. 🙂 

I'm in! 🙋‍♂️

**Comment by Taiwrash** [comment]
Hi managers,

> If it is possible that I can be added or assigned to this task. I am available to take it up!

Best, 
Rasheed.

**Comment by ada2468** [comment]
@RainbowMango karmada-bot said I need to comment to be assignee. Well, here is the comment. :D

**Comment by RainbowMango** [comment]
> If it is possible that I can be added or assigned to this task. I am available to take it up!

Sure, you definitely can join and work with @ada2468 on this task. 
But I need to be clear in advance that the window of the LFX-summer project now has been closed, so no badge and no payment for it.

**Comment by Amishakumari544** [comment]
hey, @ada2468 have you run the project on a local server? If yes can you please, connect with me I am facing some problems I want to join you for this project.

**Comment by RainbowMango** [comment]
> Sure I will be glad to join the person on the project. What's the next process?

@ada2468 Please update the status here.

**Comment by ada2468** [comment]
> > > If it is possible that I can be added or assigned to this task. I am available to take it up!
> > 
> > 
> > Sure, you definitely can join and work with @ada2468 on this task. But I need to be clear in advance that the window of the LFX-summer project now has been closed, so no badge and no payment for it.
> 
> Sure I will be glad to join the person on the project. What's the next process?

The big plan for now is to work on component level: 1. identify the components needed for our pages; 2. develop the components; 3. test it and create a PR following this [GitHub workflow guideline](https://github.com/karmada-io/karmada/blob/master/docs/contributors/guide/github-workflow.md).

Right now, I'm working on UI components and MUI theme. Besides UI, this issue also needs some work on designing a redux store, write code to handle frontend-backend communication, like implementing redux-saga/thunk and APIs for fetching data from Karmada go server. The current progress is still at early stage, you could start on anything as you see fit. To avoid massive merge conflicts in the future, it's desired to have your code loosely-coupled with others and also please create small PRs.

**Comment by Taiwrash** [comment]
> > > > If it is possible that I can be added or assigned to this task. I am available to take it up!
> > > 
> > > 
> > > Sure, you definitely can join and work with @ada2468 on this task. But I need to be clear in advance that the window of the LFX-summer project now has been closed, so no badge and no payment for it.
> > 
> > 
> > Sure I will be glad to join the person on the project. What's the next process?
> 
> @Taiwrash You are more than welcome! Here is current status.
> 
> The big plan for now is to work on component level:
> 
> 1. identify the components needed for our pages;
> 2. develop the components;
> 3. test it and create a PR following this [GitHub workflow guideline](https://github.com/karmada-io/karmada/blob/master/docs/contributors/guide/github-workflow.md).
> 
> Right now, I'm working on UI components and MUI theme. Besides UI, this issue also needs some work on designing a **redux store**, write code to handle frontend-backend communication, like **implementing redux-saga/thunk** and **APIs for fetching** data from Karmada go server. The current progress is still at early stage, you could start on anything as you see fit. To avoid massive merge conflicts in the future, it's desired to have your code loosely-coupled with others and also please create small PRs.

Thanks @ada2468 for your response. Can you create a development kit to avoid outright conflict? We can focus on only resolving features suggestions and conflicts caused.

Thanks.
