### ISSUE TITLE
Unable to login to dashboard with the token generated based on `karmada-dashboard` service account

### ISSUE THREAD

**Issue by zclyne** [karmada-io/dashboard#156]
**What happened**:

Failed to log in to karmada dashboard with the error `failed to login, please try again`.
<img width="275" alt="image" src="https://github.com/user-attachments/assets/b5c5eea6-9d65-46cc-bce0-ae06a92b78d4" /> with the token generated using the `karmada-dashboard` service account.

**What you expected to happen**: Being able to log in to karmada dashboard successfully

**How to reproduce it (as minimally and precisely as possible)**:

1. Deploy Karmada dashboard using the Helm chart in this repo.
2. Use `kubectl port-forward` to forward traffic from localhost to the frontend pod `karmada-dashboard-web-`, for example `localhost:8080`
3. Retrieve a token based on the `karmada-dashboard` service account using the following command:
```sh
kubectl create token karmada-dashboard -n karmada-system --kubeconfig <path-to-karmada-host-config>
```
4. Open `localhost:8080` in browser
5. Paste the output token into the token input box

**Anything else we need to know?**:

The response for the `POST /api/v1/login` call had status 200 but the response body is:
```
{"code":500,"message":"MSG_LOGIN_UNAUTHORIZED_ERROR","data":null}
```
It is not very intuitive to see 200 response status with a 500 code in the response body, and I am not able to tell what exactly the error is from this message.

I was not able to find any more related log in either the web pod or the api pod. Perhaps we should add more logging to karmada dashboard for easier debugging?

I'm glad to contribute if we can locate the root cause of this error.

**Environment**:
- Karmada version: An internal fork of Karmada 1.11 but we only changed scheduler and estimator, which should not affect the behavior of karmada dashboard.
- Karmada Dashboard version: Latest version as of 12/18/2024
- Others:

**Comment by zclyne** [comment]
After digging into the code I believe the error was thrown here: https://github.com/karmada-io/dashboard/blob/8ed77bdb48d05e15696c2245215c29dc82c4c3d1/pkg/client/auth.go#L55.

The root cause is here: https://github.com/karmada-io/dashboard/blob/8ed77bdb48d05e15696c2245215c29dc82c4c3d1/pkg/client/auth.go#L74-L75.

`extractBearerToken(header)` has already trimmed the `Bearer` prefix while the second line checks again if the token has a `Bearer` prefix, causing the `strings.HasPrefix` call to always return false.

I'm happy to put in a fix if you find that this is indeed a bug. Thanks!

**Comment by RainbowMango** [comment]
cc @warjiang Could you please take a look?

**Comment by warjiang** [comment]
> After digging into the code I believe the error was thrown here:
> 
> https://github.com/karmada-io/dashboard/blob/8ed77bdb48d05e15696c2245215c29dc82c4c3d1/pkg/client/auth.go#L55
> 
> .
> The root cause is here:
> 
> https://github.com/karmada-io/dashboard/blob/8ed77bdb48d05e15696c2245215c29dc82c4c3d1/pkg/client/auth.go#L74-L75
> 
> .
> `extractBearerToken(header)` has already trimmed the `Bearer` prefix while the second line checks again if the token has a `Bearer` prefix, causing the `strings.HasPrefix` call to always return false.
> 
> I'm happy to put in a fix if you find that this is indeed a bug. Thanks!

Thanks for diving into the code. You're right, but the code `strings.HasPrefix(header, authorizationTokenPrefix)` checks `header` instead of `token`.

I think the problem is that you generate the token with the `karmada-host` context in kubeconfig file(maybe the `karmada-host` is the default active context in your local kubeconfig file), you can regenerate the token with `karmada-apiserver` context like `kubectl create token karmada-dashboard -n karmada-system --kubeconfig <path-to-karmada-host-config> --context <context-name-for-karmada-apiserver>`

**Comment by zclyne** [comment]
Thanks @warjiang for your quick response.

You're right, I missed the difference between the two arguments. Thanks for catching!

I'm a bit confused about the command you suggested here - the `karmada-dashboard` service account exists in the `karmada-system` namespace on the `karmada-host` cluster but not in the karmada api server, so if I specify `--context <context-name-for-karmada-apiserver>` wouldn't it complain that the service account cannot be found?

**Comment by warjiang** [comment]
I got your problem,  something wrong with the helm chart, because you install the karmada-dashboard with the `karmada-host` context. But the `karmda-dashboard` serviceaccount should not be installed in the `karmada-host` context, it should be installed in the `karmada-apiserver` context. It seems that we should find a suitable way to make some resources be installed in the `karmada-host` context, some resources be installed in `karmada-apiserver` context.

**Comment by zclyne** [comment]
Got it. Thanks a lot for the explanation! In this case the helm chart does need to be a bit tricky since we are essentially targeting different api servers.. A potential solution I can think of is to have a one-off pod where we mount a secret that contains the kubeconfig of the `karmada-apiserver` (which is the case in our environment), and make the pod run a script to apply the service account into the `karmada-apiserver` using this kubeconfig. It is just a rough idea and would like to know if there are any other good approaches.

**Comment by warjiang** [comment]
> Got it. Thanks a lot for the explanation! In this case the helm chart does need to be a bit tricky since we are essentially targeting different api servers.. A potential solution I can think of is to have a one-off pod where we mount a secret that contains the kubeconfig of the `karmada-apiserver` (which is the case in our environment), and make the pod run a script to apply the service account into the `karmada-apiserver` using this kubeconfig. It is just a rough idea and would like to know if there are any other good approaches.

Sounds great, the method you metioned seems more elegant than mine, which will use [helm chart lifecycle](https://helm.sh/docs/topics/charts_hooks/) hooks to create the serviceaccount in the karmada-apiserver context ~

**Comment by zclyne** [comment]
Awesome! I will close this issue since we have figured out a solution. Thanks a lot for the help!
