### ISSUE TITLE
Can't get Bearer Token to login

### ISSUE THREAD

**Issue by rgrupesh** [karmada-io/dashboard#24]
**What happened**:
I ran into this error when I tried to generate Bearer Token.

![Screenshot from 2022-07-29 13-19-59](https://user-images.githubusercontent.com/54068868/181715646-db115660-2410-4fe1-b7df-4f238e504909.png)

Karmada is running locally:

![Screenshot from 2022-07-29 13-19-44](https://user-images.githubusercontent.com/54068868/181715561-cd01eb92-01a8-4739-a765-51fc937d693b.png)

**What you expected to happen**:
Generate token something like this: 

```
eyJhbGciOiJSUzI1NiIsImtpZCI6InZLdkRNclVZSFB6SUVXczBIRm8zMDBxOHFOanQxbWU4WUk1VVVpUzZwMG8ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrYXJtYWRhLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJrYXJtYWRhLWRhc2hib2FyZC10b2tlbi14NnhzcCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJrYXJtYWRhLWRhc2hib2FyZCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImE5Y2RkZDc3LTkyOWYtNGM0MS1iZDY4LWIzYWVhY2E0NGJiYiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprYXJtYWRhLXN5c3RlbTprYXJtYWRhLWRhc2hib2FyZCJ9.F0BqSxl0GVGvJZ_WNwcEFtChE7joMdIPGhv8--eN22AFTX34IzJ_2akjZcWQ63mbgr1mVY4WjYdl7KRS6w4fEQpqWkWx2Dfp3pylIcMslYRrUPirHE2YN13JDxvjtYyhBVPlbYHSj7y0rvxtfTr7iFaVRMFFiUbC3kVKNhuZtgk_tBHg4UDCQQKFALGc8xndU5nz-BF1gHgzEfLcf9Zyvxj1xLy9mEkLotZjIcnZhwiHKFYtjvCnGXxGyrTvQ5rgilAxBKv0TcmjQep_TG_Q5M9r0u8wmxhDnYd2a7wsJ3P3OnDw7smk6ikY8UzMxVoEPG7XoRcmNqhhAEutvcJoyw
```

**Anything else we need to know?**:

I am using VM on Azure. Specifications:

<pre>
H/W path      Device       Class          Description
=====================================================
                           system         Virtual Machine (None)
/0                         bus            Virtual Machine
/0/0                       memory         1MiB BIOS
/0/4                       processor      Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz
/0/6                       memory         16GiB System Memory
/0/6/0                     memory         1GiB 
/0/6/1                     memory         15GiB 
/0/2          enP64564s1   network        MT27710 Family [ConnectX-4 Lx Virtual Function]
/0/1                       communication  PnP device PNP0501
/0/3                       communication  PnP device PNP0501
/0/5                       system         PnP device PNP0b00
/0/7          scsi0        storage        
/0/7/0.0.0    /dev/sda     disk           32GB Virtual Disk
/0/7/0.0.0/1  /dev/sda1    volume         29GiB EXT4 volume
/0/7/0.0.0/e  /dev/sda14   volume         4095KiB BIOS Boot partition
/0/7/0.0.0/f  /dev/sda15   volume         105MiB Windows FAT volume
/0/7/0.0.1    /dev/sdb     disk           34GB Virtual Disk
/0/7/0.0.1/1  /dev/sdb1    volume         31GiB EXT4 volume
/1            eth0         network        Ethernet interface
/2            veth85bd3be  network        Ethernet interface
/3            veth7267d66  network        Ethernet interface
/4            veth16074fb  network        Ethernet interface
/5            veth3b9abcd  network        Ethernet interface
</pre>

**Comment by RainbowMango** [comment]
Which document are you looking? Let me try on my side.

**Comment by rgrupesh** [comment]
I'm trying to bypass token for development purposes only.

![Screenshot from 2022-08-03 18-08-36](https://user-images.githubusercontent.com/54068868/182607213-19afe8f4-8680-4ce8-a7a8-b82e917010af.png)

**Comment by 519859716** [comment]
hello  i  also get this same issue in my cluster . karmada is ready, but  get  the dashboard token to login UI ,it show request failed.
to check the karmada-apiserver log  "Unable to authenticate the request" err="invalid bearer token""  
is there any idear?

**Comment by ada2468** [comment]
The same issue. I can't test frontend API without the token.
