### ISSUE TITLE
Which api for resource bindings?

### ISSUE THREAD

**Issue by ada2468** [karmada-io/dashboard#26]
Two APIs:
/apis/work.karmada.io/v1alpha2/clusterresourcebindings
/apis/work.karmada.io/v1alpha2/resourcebindings

What are the difference? Which one should I use for our dashboard Resource Binding page?

**Comment by ada2468** [comment]
@RainbowMango

**Comment by RainbowMango** [comment]
> What are the difference?

`ClusterResourceBinding` is the `cluster-scope` resource type and `ResourceBinding` is the `namespace-scope` resource type.
From the dashboard point of view, they seem like two different APIs.

**Comment by ada2468** [comment]
I see. I'll make two separate pages to address the distinction.
