### ISSUE TITLE
Development request

### ISSUE THREAD

**Issue by XMingG99** [karmada-io/dashboard#35]
We are trying to develop a dashboard about Karmada, so we want to know the details about the dashboard image in the original project. Can you help me?

**Comment by RainbowMango** [comment]
Sure! 

> We are trying to develop a dashboard about Karmada

Do you mean to contribute to the dashboard project? 

> we want to know the details about the dashboard image in the original project.

I don't get it. are you asking for the docker image?

**Comment by XMingG99** [comment]
> Do you mean to contribute to the dashboard project?

Yes, we will try to continue this project. And we plan to do this work next mouth.

> I don't get it. are you asking for the docker image?

To be exact, we want to know the design details of this project. It is better to have data like developer documentation.

**Comment by RainbowMango** [comment]
> Yes, we will try to continue this project. And we plan to do this work next mouth.

That's great! And you are welcome to have a chat at the next [Community Meeting](https://docs.google.com/document/d/1y6YLVC-v7cmVAdbjedoyR5WL0-q45DBRXTvz5_I7bkA/edit).

**Comment by XMingG99** [comment]
> > Yes, we will try to continue this project. And we plan to do this work next mouth.
> 
> That's great! And you are welcome to have a chat at the next [Community Meeting](https://docs.google.com/document/d/1y6YLVC-v7cmVAdbjedoyR5WL0-q45DBRXTvz5_I7bkA/edit).

Thank you for your invitation, but we still need to discuss the specific plan. So maybe next time, when we are ready.

**Comment by RainbowMango** [comment]
/close
We are currently refactoring the dashboard, please look at the document on the readme file.
