### ISSUE TITLE
Can't use the token to login the karmada dashboard

### ISSUE THREAD

**Issue by whoisfisher** [karmada-io/dashboard#36]
**What happened**:
Can't use the token to login the karmada dashboard
`kubectl -n karmada-system get secret $(kubectl -n karmada-system get sa/karmada-dashboard -o jsonpath="{.secrets[0].name}") -o go-template="{{.data.token | base64decode}}"
eyJhbGciOiJSUzI1NiIsImtpZCI6InpNTGRpRktWNTUtdkh2WWRpOS1fMWpDdVpLb2FKUWJFdDRlNDU3dmk3czAifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrYXJtYWRhLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJrYXJtYWRhLWRhc2hib2FyZCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJrYXJtYWRhLWRhc2hib2FyZCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImNjMjU2ZjE2LWIxYTctNDRmNy1iMGFkLTZmYWZmYWY0NDFiNyIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprYXJtYWRhLXN5c3RlbTprYXJtYWRhLWRhc2hib2FyZCJ9.V6cnplnSBubxQDmDjVcsozz_VLsPXhhn3WYG7Fu4h5N-01wy1yOA5FeZERyCDPNWJg2gHrsGsQoOVzzuyHzagNU5R7zdWFeHxNOi3u_Yi-pvWuiULrx4qVlmI6JjPtIcUjKGFkEvZ07F19lpB8Dba8FeaVC1tkni1SQgJU2Wkxry36iRP4hajxJLV6mYqYMMHAfMB-qyvWlk02vIzPiW-kF0wuWotywpg0d11fiPZcnhW5O0ygP7rnAU5onR7oN0xFggpp1UHnQQTYzV74HCdtyJhO4wUofPjYbTvnxN1kuXppJ8jI43fAIq9AyzRs670H6GM9VP9UFBc5bkHejXcQ`
**What you expected to happen**:
Can  login the karmada dashboard
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**: 
kubernetes: v1.24.7
- Karmada version: v1.5.0
- Karmada Dashboard version: swr.ap-southeast-1.myhuaweicloud.com/karmada/karmada-dashboard:latest
- Others:

**Comment by Erick-shi** [comment]
are you have any work around? I have the same problem

**Comment by RainbowMango** [comment]
/close
We are currently refactoring the dashboard, please look at the document on the readme file.
