### ISSUE TITLE
Request sonarcloud.io Account

### ISSUE THREAD

**Issue by samzong** [karmada-io/dashboard#58]
**What would you like to be added**:

Add SonarQube as a code quality scanning tool

> SonarQube Introduction: https://docs.google.com/document/d/1UhoERlGsdfFn50CckbOt7Vv2AOpBHsbUoP8ZLeJQxl4

**Why is this needed**:

a SonarCloud account

**Comment by RainbowMango** [comment]
/assign 
Thanks. Will do.

**Comment by samzong** [comment]
make it active

**Comment by RainbowMango** [comment]
OK. try to finish it this week. sorry for the delay.

**Comment by RainbowMango** [comment]
@samzong 
Echo from [sonar FAQ](https://www.sonarsource.com/plans-and-pricing/developer/#frequently-asked-questions):
> Developer Edition, Enterprise Edition, and Data Center Edition are priced per instance per year and based on your lines of code (LOC). An instance is an installation of SonarQube. You pay per instance for a maximum number of LOC to be analyzed.


> Developer Edition pricing starts at $160/yr for a maximum analysis of 100,000 LOC and can extend to $68,580/yr for a maximum analysis of 20M LOC.

It shows that even the developer edition is not free.  Thus I'm afraid we can't integrate it due to a lack of budget.
Could you please double-check it?

**Comment by samzong** [comment]
> @samzong Echo from [sonar FAQ](https://www.sonarsource.com/plans-and-pricing/developer/#frequently-asked-questions):
> 
> > Developer Edition, Enterprise Edition, and Data Center Edition are priced per instance per year and based on your lines of code (LOC). An instance is an installation of SonarQube. You pay per instance for a maximum number of LOC to be analyzed.
> 
> > Developer Edition pricing starts at $160/yr for a maximum analysis of 100,000 LOC and can extend to $68,580/yr for a maximum analysis of 20M LOC.
> 
> It shows that even the developer edition is not free. Thus I'm afraid we can't integrate it due to a lack of budget. Could you please double-check it?

Okay, I will check it, I've seen before that open source projects are free ~

**Comment by RainbowMango** [comment]
/close
Please reopen it if this is still needed.
