### ISSUE TITLE
The shell in user-guide should be changed.

### ISSUE THREAD

**Issue by chouchongYHMing** [karmada-io/dashboard#59]
**What happened**:
In docs/user-guide.md, the shell about "run the following command to load images into the local docker space" gets a repetitive operation. It might confuse the regular users. 

**What you expected to happen**:

`cp hack/images/image.list.load.online.example cp hack/images/image.list.load.online
bash hack/ops/load-images.sh hack/images/image.list.load.online` 
should be changed by 
`cp hack/images/image.list.load.online.example
bash hack/ops/load-images.sh hack/images/image.list.load.online` 
or better solution.

**Comment by RainbowMango** [comment]
cc @warjiang 
Can you help to take a look?

**Comment by warjiang** [comment]
@chouchongYHMing thanks for your reply, it's a mistake of user-guide. 
Would you like to make a PR to correct this mistake?

**Comment by RainbowMango** [comment]
/assign @chouchongYHMing 
in favor of #60
