### ISSUE TITLE
[lfx-mentorship-2024-September-November] Collect and visualize Karmada metrics

### ISSUE THREAD

**Issue by warjiang** [karmada-io/dashboard#62]
**CNCF LFX mentorship**
https://github.com/cncf/mentoring/tree/main/programs/lfx-mentorship/2024/03-Sep-Nov

Mentor: @warjiang 

**What would you like to be added**:
Karmada dashboard now supports one-time metric retrieval, but it is difficult to observe the status of multi-clusters with one-time metric retrieval. Therefore, we would like to implement a lightweight metric collection capability to collect [Karmada metrics](https://karmada.io/docs/reference/instrumentation/metrics/) and visualize them on the Karmada dashboard. This will allow cluster administrators to quickly get the status of the clusters and solve problems within the clusters.

**Why is this needed**:

**Comment by upsaurav12** [comment]
Hello everyone,
I am Saurav Upadhyay , interested on contributing on this project. i have solid understanding in Golang and also build some projects in Gin Framework. Additionally, I have some experience with React.js, having worked on a few projects using it.
 i am also currently learning Kubernetes. i am very excited to bring my skills on project to make meaningful impact by my contributions

**Comment by HarshitNagpal29** [comment]
Hi @warjiang,

I hope you're doing well. I'm very interested in contributing to the Karmada metrics collection and visualization project as part of the CNCF LFX mentorship for September-November 2024. I have a few questions to ensure I approach this project correctly:

1. Should the metric collection capability be implemented as a separate lightweight service, or should it be integrated directly into the existing Karmada dashboard?

2. Are there specific metrics that should be prioritized for collection and visualization beyond the basic cluster status metrics?

Any guidance or resources you could provide would be extremely helpful. I believe I have the skills and enthusiasm required to make meaningful contributions to this project.

Thank you!

**Comment by xyz-3** [comment]
Hi @warjiang @XiShanYongYe-Chang I am interested in working on this issue under LFX, can you give me some guidance on where to start or is there any pre tasks that i would need to do? Thanks!
