### ISSUE TITLE
About "the following command to start the test cluster"

### ISSUE THREAD

**Issue by chouchongYHMing** [karmada-io/dashboard#63]
**What happened**:
When I executive this shell:
```
bash hack/local-up-karmada.sh
```
My server of karmada-apiserver will be forced to change to 127:0:0:1 in karmada.config. But my local server of  karmada-host-control-plane is 172.18.0.3. It's queried by the shell like this:
```
docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}'  "CONTAINER ID of karmada-host-control-plane"
```
So that, I unable to execute the shell:
```
kubectl apply -f artifacts/dashboard/karmada-dashboard-sa.yaml
```
The error will be located at: 
```
[2024-07-20 20:47:50][INFO  ][main:299] Create namespace on karmada-apiserver
error: error validating "/var/folders/rw/254jjhsx2758fk20v9btxgcm0000gn/T/tmp.19wJcCm5ry/deploy/namespace.yaml": error validating data: failed to download openapi: Get "https://127.0.0.1:5443/openapi/v2?timeout=32s": dial tcp 127.0.0.1:5443: connect: connection refused; if you choose to ignore these errors, turn validation off with --validate=false
[2024-07-20 20:47:50][INFO  ][main:300] 
```
**What you expected to happen**:
I expected the command can be optimized to fit the local environment.
**How to reproduce it (as minimally and precisely as possible)**:
If we ignore the error and continue, this situation will occur after "apply"
```
base) yuhowmean@192 dashboard % kubectl apply -f artifacts/dashboard/karmada-dashboard-sa.yaml
clusterrolebinding.rbac.authorization.k8s.io/karmada-dashboard created
Error from server (NotFound): error when creating "artifacts/dashboard/karmada-dashboard-sa.yaml": namespaces "karmada-system" not found
Error from server (NotFound): error when creating "artifacts/dashboard/karmada-dashboard-sa.yaml": namespaces "karmada-system" not found
``` 
**Anything else we need to know?**:
If we create namespace of karmada-system manually, like this:
```
kubectl create namespace karmada-system
```
The problem that the token is empty will occur, like this:
```
(base) yuhowmean@OminMacBook-Pro ~ % kubectl -n karmada-system get secret/karmada-dashboard-secret -ojsonpath='{.data.token}' | base64 -d && echo



(base) yuhowmean@OminMacBook-Pro ~ %
```
And the number of DATA is 0.
**Environment**:
- Karmada version:The latest version
- Karmada Dashboard version:The latest 
- Others:

**Comment by warjiang** [comment]
It seems that the process of starting  karmada test environment broken, the karmada-system namespace did not be created correctly. After that you create karmada-system namespace manually. I'll try to recurrent the strange problem. @chouchongYHMing and you can try start the test environment by `bash local-up-karmada.sh ${you host ip address}`.
