### ISSUE TITLE
UI界面登不上去

### ISSUE THREAD

**Issue by Erick-shi** [karmada-io/dashboard#67]
当生产token后， token应该是一行，可是粘贴到了web节目中，就换行了，，，是不是bug呢？
![image](https://github.com/user-attachments/assets/7e4cc8ef-190a-4447-afd0-f38e8959e559)

**Comment by warjiang** [comment]
It's the view of textarea, in fact no `\r\n` in the textarea component, maybe you can double check it by view the request in the network panel.

**Comment by warjiang** [comment]
Is it the same issue with the https://github.com/karmada-io/dashboard/issues/66,  if true we can solve the problem in dedicated issue.

**Comment by axif0** [comment]
@warjiang i generated the token which mentioned [Here](https://github.com/karmada-io/dashboard/blob/main/docs/user-guide.md#installation-of-karmada-dashboard). And make `karmada-dashboard-api` run the front-end by seeing [here](https://github.com/karmada-io/dashboard/blob/main/DEVELOPMENT.md#getting-started). I couldn't login. 

Also in input field, I see when `-`  found it creates a new line. also in `Authorization`. How can I solve the issue. can you please tell ?

![image](https://github.com/user-attachments/assets/add90119-c6ff-4622-b248-3b9ee12bd773)

**Comment by warjiang** [comment]
> @warjiang i generated the token which mentioned [Here](https://github.com/karmada-io/dashboard/blob/main/docs/user-guide.md#installation-of-karmada-dashboard). And make `karmada-dashboard-api` run the front-end by seeing [here](https://github.com/karmada-io/dashboard/blob/main/DEVELOPMENT.md#getting-started). I couldn't login.
> 
> Also in input field, I see when `-` found it creates a new line. also in `Authorization`.
> 
> How can I solve the issue for login. can you please tell ?
> 
> ![image](https://private-user-images.githubusercontent.com/66010854/352780850-add90119-c6ff-4622-b248-3b9ee12bd773.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMDcxMTUsIm5iZiI6MTcyMjMwNjgxNSwicGF0aCI6Ii82NjAxMDg1NC8zNTI3ODA4NTAtYWRkOTAxMTktYzZmZi00NjIyLWIyNDgtM2I5ZWUxMmJkNzczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDAyMzMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1ZGZmMDNjY2ZlOTJlMmM0NWIwODRhMjYxMTRmMDU4MTlhMzQ0NmIxY2JkNzRkMWI5YzIxYzA5MTE2OWU1YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MQmeE4JqfbMXU9ShtiPraASrygwk_lZidkJ_bPn1yog)
> 
> `(solved)` Runing Karmada Dashboard API server and i can login as well
> 
> _output/bin/linux/amd64/karmada-dashboard-api --karmada-kubeconfig=/home/asif/.kube/karmada.config --karmada-context=karmada-apiserver --skip-karmada-apiserver-tls-verify --kubeconfig=/home/asif/.kube/karmada.config --context=karmada-host --insecure-port=8000

It seems that you've already solved it by yourself, right ?

**Comment by axif0** [comment]
@warjiang yaa... thank you.

**Comment by Erick-shi** [comment]
@warjiang , so how I can solve it?

**Comment by warjiang** [comment]
> @warjiang , so how I can solve it?

@Erick-shi  can you inspect the network xhr request in the browser dev tools, when you click login, it will be an `login` request be sent, you can filter the xhr request by keyword `login`, it will give me more details about this question

**Comment by Erick-shi** [comment]
> > @warjiang , so how I can solve it?
> 
> @Erick-shi can you inspect the network xhr request in the browser dev tools, when you click login, it will be an `login` request be sent, you can filter the xhr request by keyword `login`, it will give me more details about this issue

![image](https://github.com/user-attachments/assets/a5300c61-ba49-4737-b1e0-8651249337cc)

![image](https://github.com/user-attachments/assets/a3959e3f-b232-482a-9ea0-0d05ed8d2afd)

**Comment by axif0** [comment]
@Erick-shi hello, did you run the `karmada-dashboard-api` ? I also face the problem. After running the api I solved it.

**Comment by Erick-shi** [comment]
> @Erick-shi hello, did you run the `karmada-dashboard-api` ? I also face the problem. After running the api I solved it.

hello, that's my karmada pod 
```bash

kube-controller-manager-7b94cb494f-knlv9        0/1     CrashLoopBackOff   64 (22s ago)    17d
[root@k8scluster-manager ~]# kubectl -n karmada-system get pod
NAME                                            READY   STATUS    RESTARTS         AGE
etcd-0                                          1/1     Running   14 (2m38s ago)   17d
karmada-aggregated-apiserver-564c75f4d6-nzqv5   1/1     Running   36 (80s ago)     17d
karmada-apiserver-54bc5656f4-rb898              1/1     Running   17 (110s ago)    17d
karmada-controller-manager-76f67d8f77-n8xlh     1/1     Running   68 (76s ago)     17d
karmada-dashboard-6649bd5d8d-kxkmc              1/1     Running   21 (2m ago)      17d
karmada-dashboard-api-68f4cd9c55-lg549          1/1     Running   11 (76s ago)     3d23h
karmada-dashboard-web-6bb6f998f8-vq25w          1/1     Running   3 (2m38s ago)    4d
karmada-scheduler-55d78d87dc-8jcwl              1/1     Running   44 (2m38s ago)   17d
karmada-webhook-586d65d978-2pkv2                1/1     Running   12 (2m38s ago)   17d
kube-controller-manager-7b94cb494f-knlv9        1/1     Running   65 (71s ago)     17d
[root@k8scluster-manager ~]#
```
I have run the `karmada-dashboard-api` but I had't login the dashboard.  could you have any word around?

**Comment by warjiang** [comment]
> > > @warjiang , so how I can solve it?
> > 
> > 
> > @Erick-shi can you inspect the network xhr request in the browser dev tools, when you click login, it will be an `login` request be sent, you can filter the xhr request by keyword `login`, it will give me more details about this issue
> 
> ![image](https://private-user-images.githubusercontent.com/16409629/356180359-a5300c61-ba49-4737-b1e0-8651249337cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0MzQ3NjIsIm5iZiI6MTcyMzQzNDQ2MiwicGF0aCI6Ii8xNjQwOTYyOS8zNTYxODAzNTktYTUzMDBjNjEtYmE0OS00NzM3LWIxZTAtODY1MTI0OTMzN2NjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDAzNDc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0YzIzMTcxZmVkMTgyZjA2YWFkOTNmOWU5MmYzNDI3YWU1ZTg5NGU0ZjVhMDE0YWI2NmJiZTFmZDE2N2U3YTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8cJmWocSumYjuWdDc5CA-cp-CiSPV7MeB5ja8h7HZgU)
> 
> ![image](https://private-user-images.githubusercontent.com/16409629/356181080-a3959e3f-b232-482a-9ea0-0d05ed8d2afd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0MzQ3NjIsIm5iZiI6MTcyMzQzNDQ2MiwicGF0aCI6Ii8xNjQwOTYyOS8zNTYxODEwODAtYTM5NTllM2YtYjIzMi00ODJhLTllYTAtMGQwNWVkOGQyYWZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDAzNDc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2MWE0OTQ5MTc2MWYyN2FkZDA0ZDkyY2EyMWJhZTQzMGM0MzgyODgyYzA2YTk1ZjAzZTczYTEwYjYwYzZkZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fjzS8BTk1OuODhMx0hOYyMVyTVl4dr1phHIDfp6ysdc)

Hi @Erick-shi , are you trying two kind of our dashboard? The above one is our new dashboard, the one at the bottom is the old version.

**Comment by Erick-shi** [comment]
> > > > @warjiang , so how I can solve it?
> > > 
> > > 
> > > @Erick-shi can you inspect the network xhr request in the browser dev tools, when you click login, it will be an `login` request be sent, you can filter the xhr request by keyword `login`, it will give me more details about this issue
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/16409629/356180359-a5300c61-ba49-4737-b1e0-8651249337cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0MzQ3NjIsIm5iZiI6MTcyMzQzNDQ2MiwicGF0aCI6Ii8xNjQwOTYyOS8zNTYxODAzNTktYTUzMDBjNjEtYmE0OS00NzM3LWIxZTAtODY1MTI0OTMzN2NjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDAzNDc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0YzIzMTcxZmVkMTgyZjA2YWFkOTNmOWU5MmYzNDI3YWU1ZTg5NGU0ZjVhMDE0YWI2NmJiZTFmZDE2N2U3YTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8cJmWocSumYjuWdDc5CA-cp-CiSPV7MeB5ja8h7HZgU)
> > ![image](https://private-user-images.githubusercontent.com/16409629/356181080-a3959e3f-b232-482a-9ea0-0d05ed8d2afd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0MzQ3NjIsIm5iZiI6MTcyMzQzNDQ2MiwicGF0aCI6Ii8xNjQwOTYyOS8zNTYxODEwODAtYTM5NTllM2YtYjIzMi00ODJhLTllYTAtMGQwNWVkOGQyYWZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDAzNDc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2MWE0OTQ5MTc2MWYyN2FkZDA0ZDkyY2EyMWJhZTQzMGM0MzgyODgyYzA2YTk1ZjAzZTczYTEwYjYwYzZkZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fjzS8BTk1OuODhMx0hOYyMVyTVl4dr1phHIDfp6ysdc)
> 
> Hi @Erick-shi , are you trying two kind of our dashboard? The above one is our new dashboard, the one at the bottom is the old version.

yes, the two dashboard I have  to try,but all is failed.

**Comment by warjiang** [comment]
For the newer dashboard, are you still using the same sa token as before or re-generate a new one? Are you using the guide: https://github.com/karmada-io/dashboard/blob/main/docs/user-guide.md

**Comment by Erick-shi** [comment]
> For the newer dashboard, are you still using the same sa token as before or re-generate a new one? Are you using the guide: https://github.com/karmada-io/dashboard/blob/main/docs/user-guide.md
> 
> When generating sa token, you should use the right context: ![image](https://private-user-images.githubusercontent.com/6478745/356933235-089dc424-6602-44dc-8b60-482a57377a76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NDQ2NTUsIm5iZiI6MTcyMzQ0NDM1NSwicGF0aCI6Ii82NDc4NzQ1LzM1NjkzMzIzNS0wODlkYzQyNC02NjAyLTQ0ZGMtOGI2MC00ODJhNTczNzdhNzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTJUMDYzMjM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDJjNWNiOTQ0MWE3YjE3ZDE2NTU3YTdjNGFkMGQyYzgwZGE2YjIwZThiN2EzYTBhYzgxNWM2NThmZjZmM2U4NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9PIYkxyY0T7C5jDt3AwRmZ3AkMLwi5w5TIEtgeJ_7Ow)

I   had to try use 
```bash
[root@k8scluster-manager dashboard]# export KUBECONFIG=${HOME}/.kube/karmada.config
[root@k8scluster-manager dashboard]# kubectl config use-context karmada-host
Switched to context "karmada-host".
[root@k8scluster-manager dashboard]# kubectl apply -f  karmada-dashboard-sa.yaml
error: error validating "karmada-dashboard-sa.yaml": error validating data: failed to download openapi: the server could not find the requested resource; if you choose to ignore these errors, turn validation off with --validate=false
[root@k8scluster-manager dashboard]#
```
I am use `kubectl karmada init`  install the karmada, Is this error related to this?

**Comment by Erick-shi** [comment]
> > For the newer dashboard, are you still using the same sa token as before or re-generate a new one? Are you using the guide: https://github.com/karmada-io/dashboard/blob/main/docs/user-guide.md
> > When generating sa token, you should use the right context: ![image](https://private-user-images.githubusercontent.com/6478745/356933235-089dc424-6602-44dc-8b60-482a57377a76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NDQ2NTUsIm5iZiI6MTcyMzQ0NDM1NSwicGF0aCI6Ii82NDc4NzQ1LzM1NjkzMzIzNS0wODlkYzQyNC02NjAyLTQ0ZGMtOGI2MC00ODJhNTczNzdhNzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTJUMDYzMjM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDJjNWNiOTQ0MWE3YjE3ZDE2NTU3YTdjNGFkMGQyYzgwZGE2YjIwZThiN2EzYTBhYzgxNWM2NThmZjZmM2U4NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9PIYkxyY0T7C5jDt3AwRmZ3AkMLwi5w5TIEtgeJ_7Ow)
> 
> I had to try use
> 
> ```shell
> [root@k8scluster-manager dashboard]# export KUBECONFIG=${HOME}/.kube/karmada.config
> [root@k8scluster-manager dashboard]# kubectl config use-context karmada-host
> Switched to context "karmada-host".
> [root@k8scluster-manager dashboard]# kubectl apply -f  karmada-dashboard-sa.yaml
> error: error validating "karmada-dashboard-sa.yaml": error validating data: failed to download openapi: the server could not find the requested resource; if you choose to ignore these errors, turn validation off with --validate=false
> [root@k8scluster-manager dashboard]#
> ```
> 
> I am use `kubectl karmada init` install the karmada, Is this error related to this?

@warjiang  hi, I have solve my problem
I must change the context to  karmada-apiserver
```bash
export KUBECONFIG=/etc/karmada/karmada-apiserver.config
```
thanks.

**Comment by RainbowMango** [comment]
/close
As issue has been resolved.
