### ISSUE TITLE
How to resolve etcd pod stuck in ContainerCreating state during Karmada setup?

### ISSUE THREAD

**Issue by axif0** [karmada-io/dashboard#68]
**Environment**:
- Karmada version: N/A
- Karmada Dashboard version: N/A
- Others:N/A 

During Karmada setup when i run `hack/local-up-karmada.sh`, the etcd pod is stuck in ContainerCreating state:

![image](https://github.com/user-attachments/assets/58819cb6-436b-4742-b714-a200087a55ba)

in kubectl describe info i got

 ```
kubectl describe info:
Name:             etcd-0
Namespace:        karmada-system
Priority:         0
Service Account:  default
Node:             karmada-host-control-plane/172.18.0.4
Start Time:       Fri, 26 Jul 2024 16:12:00 +0600
Labels:           app=etcd
                  controller-revision-hash=etcd-5bd9b698bf
                  statefulset.kubernetes.io/pod-name=etcd-0
Annotations:      <none>
Status:           Pending
IP:               
IPs:              <none>
Controlled By:    StatefulSet/etcd
Containers:
  etcd:
    Container ID:  
    Image:         registry.k8s.io/etcd:3.5.13-0
    Image ID:      
    Ports:         2379/TCP, 2380/TCP
    Host Ports:    0/TCP, 0/TCP
    Command:
      /usr/local/bin/etcd
      --name
      etcd0
      --listen-peer-urls
      http://0.0.0.0:2380
      --listen-client-urls
      https://0.0.0.0:2379
      --advertise-client-urls
      https://etcd-client.karmada-system.svc.cluster.local:2379
      --initial-cluster
      etcd0=http://etcd-0.etcd.karmada-system.svc.cluster.local:2380
      --initial-cluster-state
      new
      --cert-file=/etc/karmada/pki/etcd-server.crt
      --client-cert-auth=true
      --key-file=/etc/karmada/pki/etcd-server.key
      --trusted-ca-file=/etc/karmada/pki/etcd-ca.crt
      --data-dir=/var/lib/etcd
      --snapshot-count=10000
      --cipher-suites=TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_AES_128_GCM_SHA256,TLS_AES_256_GCM_SHA384,TLS_CHACHA20_POLY1305_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:        100m
      memory:     100Mi
    Liveness:     exec [/bin/sh -ec etcdctl get /registry --prefix --keys-only  --endpoints https://127.0.0.1:2379  --cacert /etc/karmada/pki/etcd-ca.crt --cert /etc/karmada/pki/etcd-server.crt --key /etc/karmada/pki/etcd-server.key] delay=600s timeout=10s period=60s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /etc/karmada/pki from etcd-certs (rw)
      /var/lib/etcd from etcd-data (rw)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  etcd-data:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/karmada-etcd
    HostPathType:  DirectoryOrCreate
  etcd-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  karmada-cert-secret
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     op=Exists
Events:
  Type    Reason     Age    From               Message
  ----    ------     ----   ----               -------
  Normal  Scheduled  5m41s  default-scheduler  Successfully assigned karmada-system/etcd-0 to karmada-host-control-plane
  Normal  Pulling    5m40s  kubelet            Pulling image "registry.k8s.io/etcd:3.5.13-0"
kubectl logs info:
Error from server (BadRequest): container "etcd" in pod "etcd-0" is waiting to start: ContainerCreating

```
How do i solve the issue to run Karmada cluster for the dashboard? 

cc : @warjiang

**Comment by warjiang** [comment]
Can you provide more context, by executing the following code

```
kubectl --kubeconfig ~/.kube/karmada.config --context karmada-host -n karmada-system get pod
kubectl --kubeconfig ~/.kube/karmada.config --context=karmada-host -n karmada-system logs etcd-0 > etcd.log
```

**Comment by warjiang** [comment]
> **Environment**:
> 
> * Karmada version: N/A
> * Karmada Dashboard version: N/A
> * Others:N/A
> 
> During Karmada setup when i run `hack/local-up-karmada.sh`, the etcd pod is stuck in ContainerCreating state:
> 
> ![image](https://private-user-images.githubusercontent.com/66010854/352514705-58819cb6-436b-4742-b714-a200087a55ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwMDUzMDIsIm5iZiI6MTcyMjAwNTAwMiwicGF0aCI6Ii82NjAxMDg1NC8zNTI1MTQ3MDUtNTg4MTljYjYtNDM2Yi00NzQyLWI3MTQtYTIwMDA4N2E1NWJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDE0NDMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1YTY4MjE2Y2ZlZDg4OTc0YTQ5N2E3Y2Q3ZDRlODNkOTRmYjBmYjMzMTgxZTMzMmU4M2RjYTFiZTU2ZDAzMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RS43PRcU1hSCrYJZuRRyLem69rM4InlyYtrTVdEU6Ow)
> 
> in kubectl describe info i got
> 
> ```
> kubectl describe info:
> Name:             etcd-0
> Namespace:        karmada-system
> Priority:         0
> Service Account:  default
> Node:             karmada-host-control-plane/172.18.0.4
> Start Time:       Fri, 26 Jul 2024 16:12:00 +0600
> Labels:           app=etcd
>                  controller-revision-hash=etcd-5bd9b698bf
>                  statefulset.kubernetes.io/pod-name=etcd-0
> Annotations:      <none>
> Status:           Pending
> IP:               
> IPs:              <none>
> Controlled By:    StatefulSet/etcd
> Containers:
>  etcd:
>    Container ID:  
>    Image:         registry.k8s.io/etcd:3.5.13-0
>    Image ID:      
>    Ports:         2379/TCP, 2380/TCP
>    Host Ports:    0/TCP, 0/TCP
>    Command:
>      /usr/local/bin/etcd
>      --name
>      etcd0
>      --listen-peer-urls
>      http://0.0.0.0:2380
>      --listen-client-urls
>      https://0.0.0.0:2379
>      --advertise-client-urls
>      https://etcd-client.karmada-system.svc.cluster.local:2379
>      --initial-cluster
>      etcd0=http://etcd-0.etcd.karmada-system.svc.cluster.local:2380
>      --initial-cluster-state
>      new
>      --cert-file=/etc/karmada/pki/etcd-server.crt
>      --client-cert-auth=true
>      --key-file=/etc/karmada/pki/etcd-server.key
>      --trusted-ca-file=/etc/karmada/pki/etcd-ca.crt
>      --data-dir=/var/lib/etcd
>      --snapshot-count=10000
>      --cipher-suites=TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_AES_128_GCM_SHA256,TLS_AES_256_GCM_SHA384,TLS_CHACHA20_POLY1305_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
>    State:          Waiting
>      Reason:       ContainerCreating
>    Ready:          False
>    Restart Count:  0
>    Requests:
>      cpu:        100m
>      memory:     100Mi
>    Liveness:     exec [/bin/sh -ec etcdctl get /registry --prefix --keys-only  --endpoints https://127.0.0.1:2379  --cacert /etc/karmada/pki/etcd-ca.crt --cert /etc/karmada/pki/etcd-server.crt --key /etc/karmada/pki/etcd-server.key] delay=600s timeout=10s period=60s #success=1 #failure=3
>    Environment:  <none>
>    Mounts:
>      /etc/karmada/pki from etcd-certs (rw)
>      /var/lib/etcd from etcd-data (rw)
> Conditions:
>  Type              Status
>  Initialized       True 
>  Ready             False 
>  ContainersReady   False 
>  PodScheduled      True 
> Volumes:
>  etcd-data:
>    Type:          HostPath (bare host directory volume)
>    Path:          /var/lib/karmada-etcd
>    HostPathType:  DirectoryOrCreate
>  etcd-certs:
>    Type:        Secret (a volume populated by a Secret)
>    SecretName:  karmada-cert-secret
>    Optional:    false
> QoS Class:       Burstable
> Node-Selectors:  <none>
> Tolerations:     op=Exists
> Events:
>  Type    Reason     Age    From               Message
>  ----    ------     ----   ----               -------
>  Normal  Scheduled  5m41s  default-scheduler  Successfully assigned karmada-system/etcd-0 to karmada-host-control-plane
>  Normal  Pulling    5m40s  kubelet            Pulling image "registry.k8s.io/etcd:3.5.13-0"
> kubectl logs info:
> Error from server (BadRequest): container "etcd" in pod "etcd-0" is waiting to start: ContainerCreating
> ```
> 
> How do i solve the issue to run Karmada cluster for the dashboard?
> 
> cc : @warjiang

From the events showed above, it seems that the kubelet is trying to pull the "registry.k8s.io/etcd:3.5.13-0" image, but no any more events occured. Can you try to pull the image  and load it in the kind cluster manually
```
docker pull registry.k8s.io/etcd:3.5.13-0
kind load docker-image registry.k8s.io/etcd:3.5.13-0 --name karmada-host
```

**Comment by axif0** [comment]
Thank you so much @warjiang for your kind suggestion. It solved right away.

**Comment by mhmohona** [comment]
I was also facing similar problem. Thank you @warjiang for the solve.
