### ISSUE TITLE
Metrics Server Deployment Failing: Certificate Validation Error

### ISSUE THREAD

**Issue by axif0** [karmada-io/dashboard#72]
**Please provide an in-depth description of the question you have**:

![image](https://github.com/user-attachments/assets/cef53f63-ed7c-4241-b9e3-4374c953981a)

**What do you think about this question?**:

Hello, @warjiang @XiShanYongYe-Chang , Please advise on how to resolve this certificate validation issue and successfully deploy the [metrics-server](https://github.com/karmada-io/dashboard/blob/d23208ae9cd99dcf9f258140991856c4cf6d7fbf/artifacts/metrics-server.yaml#L1)

**Environment**:
- Karmada version: latest
- Karmada Dashboard version: `0.1.0`
- Others: N/A

**Comment by warjiang** [comment]
@axif0 can you show your `karmada.config` file

**Comment by warjiang** [comment]
@axif0 Where you did you deploy the metrics-sever,  on the control-plane or on the member cluster
If you start the environment by local-up-karmada.sh, then it will install metrics-server on member cluster 
https://github.com/karmada-io/dashboard/blob/d23208ae9cd99dcf9f258140991856c4cf6d7fbf/hack/local-up-karmada.sh#L240C1-L250C1

**Comment by axif0** [comment]
![image](https://github.com/user-attachments/assets/f9eb0325-ed82-44ff-9508-e73b09910ad9)

@warjiang  Can you please how can i access cluster_sync_status_duration_seconds for member1 cluster? 

[Karmada Metrics Reference](https://karmada.io/docs/reference/instrumentation/metrics/)

**Comment by axif0** [comment]
![image](https://github.com/user-attachments/assets/f9eb0325-ed82-44ff-9508-e73b09910ad9)

@warjiang  Can you please tell how can i access/see in command terminal `cluster_sync_status_duration_seconds` or different Karmada components which mentioned in [Karmada Metrics Reference](https://karmada.io/docs/reference/instrumentation/metrics/) for member1 cluster?  Should we use Prometheus for monitoring ? 

i installed metrics-server as running `hack/local-up-karmada.sh`, i'm sorry i didn't check the file. i instaled metrics-server on member clusters

**Comment by warjiang** [comment]
You can execute the following instructions: 
```
kubectl --kubeconfig ~/.kube/karmada.config --context karmada-host  -n karmada-system get po -l app=karmada-controller-manager
```
it will output like this: 
![image](https://github.com/user-attachments/assets/523db64f-5636-43b4-ac8a-fa8fd5555370)

Things you should be careful are that karmada-controller-manager worked in master-slave architecture, only one pod will output the related metrics.

```
pod_name=karmada-controller-manager-54d9c78689-2ft65
kubectl --kubeconfig ~/.kube/karmada.config --context karmada-host   get --raw /api/v1/namespaces/karmada-system/pods/${pod_name}:8080/proxy/metrics|grep cluster_sync_status_duration_seconds
```
in my case, the first one is master, so it output:
![image](https://github.com/user-attachments/assets/60ff15b3-7ef1-4aca-9e8a-92149e2e0899)

**Comment by warjiang** [comment]
the cluster_sync_status_duration_seconds metric has label `cluster_name`, so you can filter it by label_name

**Comment by warjiang** [comment]
@axif0 i metioned that you seems have great interest about the metrics scraping, can you tell me more about your use-case?

**Comment by axif0** [comment]
Some metrics like histogram/Gauge/Counter are not visualized in dashboard. I'm trying to implement those Karmada Metrics in the dashboard. 

@warjiang I wanted to contribute in karmada. Later I seen this is selected by [LFX](https://github.com/karmada-io/dashboard/issues/62).

**Comment by jayesh9747** [comment]
![WhatsApp Image 2024-07-30 at 9 42 07 PM](https://github.com/user-attachments/assets/fd604835-dee7-4895-ad54-49f022fffbe7)


can you tell me how to resolve this error ? or what ever step you follow to deploy the api-server or control plane or dashboard.

**Comment by axif0** [comment]
hello .. @jayesh9747 did you configure first? 

`export KUBECONFIG=${HOME}/.kube/karmada.config`

**Comment by jayesh9747** [comment]
hello @axif0   I have tried using the given document by you 
![image](https://github.com/user-attachments/assets/0e1b8f4e-fab4-4fc4-af20-a05fb32e1505)
but still `this waiting for ok...` is shown to me  after run  this command `bash hack/local-up-karmada.sh`

**Comment by jayesh9747** [comment]
> hello .. @jayesh9747 did you configure first?
> 
> `export KUBECONFIG=${HOME}/.kube/karmada.config` . you can check this out [here](https://github.com/karmada-io/dashboard/blob/main/docs/user-guide.md#installation-of-karmada-dashboard)

and it is the next step after running this command but i stuck before execute this command

**Comment by axif0** [comment]
Hello, @jayesh9747 Are you prepare and download all required images in your local machine ?
if not then please try, 
```
cp hack/images/image.list.load.online.example hack/images/image.list
bash hack/ops/load-images.sh hack/images/image.list
```
