### ISSUE TITLE
Reading Karmada Metrics

### ISSUE THREAD

**Issue by axif0** [karmada-io/dashboard#73]
**Please provide an in-depth description of the question you have**:

Based on [here](https://karmada.io/docs/reference/instrumentation/metrics/) I manage to find these metrics with your help [here](https://github.com/karmada-io/dashboard/issues/72#issuecomment-2258310312) . When debugging i tried 

```kubectl` --kubeconfig ~/.kube/karmada.config --context karmada-host get --raw `/api/v1/namespaces/karmada-system/pods/${pod_name}:8080/proxy/metrics``` . it show all the available metrics results in karmada-host. But I failed to find all metrics. 

![image](https://github.com/user-attachments/assets/adbd5214-336c-4596-abc1-344d7c17cbf3) 

 How can I get other metrics results to show on dashboard? Can you please give me suggestion?  @warjiang 

 

Environment:

Karmada version: latest
Karmada Dashboard version: 0.1.0
Others: N/A

**Comment by warjiang** [comment]
@axif0 sorry late for the reply. Thanks for your enthusiasm first.
The way to fetch metcis you metioned above only can fetch metrics from karmada-controller-manager. In fact, the metrics spread in many karmada components across `control plane` and ` member cluser`(for pull mode only). I'll provide a more detailed document here and under the lfx issue(I'm try my best to translate the doc 🚀  ).

**Comment by axif0** [comment]
So, based on this, using, 
```
kubectl --kubeconfig ~/.kube/karmada.config --context karmada-host get pods -n karmada-system -l app=karmada-scheduler -o jsonpath='{.items[1].metadata.name}'
```
```
pod_name=karmada-scheduler-7bd4659f9f-s2mzv
```
```
kubectl --kubeconfig ~/.kube/karmada.config --context karmada-host get --raw /api/v1/namespaces/karmada-system/pods/${pod_name}:10351/proxy/metrics | grep 'schedule_attempts_total'
```
I got the `schedule_attempts_total`. Thank you, @warjiang 

Any suggestion regarding selecting master pod or from where i can learn? Because i'll have to always check for `jsonpath='{.items[1].metadata.name}` or `jsonpath='{.items[0].metadata.name}` ?
