### ISSUE TITLE
Prepare for the first realese and list the todos for the new dashboard

### ISSUE THREAD

**Issue by warjiang** [karmada-io/dashboard#76]
**What would you like to be added**:
Thus we already implementd cluster、resource、kind of strategy management(including propagation policy) and basic configuration of dashboard(including helm and docker registry), so I want to 

some snapshot of the current work as following:
- overview:
   ![image](https://github.com/user-attachments/assets/25d3f0bf-9d77-424b-b330-b5aac39aa4da)
-  Multi cloud resource management: 
   namespace:
   ![image](https://github.com/user-attachments/assets/d55c6fd1-96cc-44bd-804c-fb7bfaf12e74)
   deployment:
   ![image](https://github.com/user-attachments/assets/42cd2509-bade-464c-90c4-9a9f3af6daa8)
   statefulset:
   ![image](https://github.com/user-attachments/assets/319123b8-5c2d-4115-8538-fe1ec873be16)
   cronjob:
   ![image](https://github.com/user-attachments/assets/40acb395-ceaa-4498-83af-f3228a47a873)
   service:   
   ![image](https://github.com/user-attachments/assets/e8db46d6-892e-4d2e-a30d-5d052d93485a)
   configmap:
   ![image](https://github.com/user-attachments/assets/e5b4ee4c-ef10-49dd-9df7-9bad246d7cfe)
   namespaced propagation policy:
   ![image](https://github.com/user-attachments/assets/ee84d6e7-af59-4358-86c7-7d308fb5570a)
   cluster-wide propagation policy:
   ![image](https://github.com/user-attachments/assets/4da9a6e4-b233-4c60-8ffb-80d2eb5c2ab7)
- cluster management:   
   ![image](https://github.com/user-attachments/assets/9236050c-be7f-4e40-8149-27a6a47d92ea)

**Why is this needed**:
Wants to list todos for the first release
- [x] full translation of i18n text
- [x] i18n-cli(may be wip) will be ok https://github.com/karmada-io/dashboard/pull/131
- [x] Prepare the pr of complement work and waiting for review
   - [x] workload(100% deployment、statefulset、daemonset are done, cronjob、job are on the way, pr for api was already merged, only one pr for ui management should be merged) https://github.com/karmada-io/dashboard/pull/111 & https://github.com/karmada-io/dashboard/pull/112 & https://github.com/karmada-io/dashboard/pull/137
   - [x] sevice(100% the related api has been merged) https://github.com/karmada-io/dashboard/pull/139
   - [x] config(100% finished configmap & secret) https://github.com/karmada-io/dashboard/pull/99
- [x] Expose service through ingress or nodeport, or let the end-user select https://github.com/karmada-io/dashboard/pull/104/files
- [x] Override policy, which will be implemented by ospp. Currently, we've already finished the work by ourselves.
- [x] Configuration of karmada components 
   this will be hold on, and will be implemented by community contributors -> https://github.com/karmada-io/dashboard/pull/84
- [x] New readme for the refactored karmada dashboard https://github.com/karmada-io/dashboard/pull/105
- [x] Remove the old one https://github.com/karmada-io/dashboard/pull/130

**Comment by RainbowMango** [comment]
Congrats! 
Seems all tasks done.
We can start to cut a new release.

/close
